[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "myrage"
version = "0.0.23"
description = "A simple class to instanciate a tor process and run http requests behind it"
authors = [
	{ name = "Cyril Quijoux" }
]
keywords = ['tor', 'requests', 'http', 'https']

dependencies = [
	"requests==2.32.5",
	"requests[socks]",
	"stem==1.8.2",
	"psutil==7.0.0",
	"decolog==0.0.5"
]

[tool.ruff.lint]
extend-select = ["E"]

[tool.ruff]
line-length = 88

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

[tool.setuptools.packages.find]
where = ['src']
